version: "2"
services:
  postgres:
    image: postgres # 14.5
    ports:
      - "5432:5432" # remove this if you dont want to use db from host...
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  pgadmin: 
    image: dpage/pgadmin4
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  