version: '2'

services:

  broker:
    image: harispy/broker
    ports:
      - "8080:8080"
    environment:
      - BROKER_DATABASE=cassandra
      - BROKER_DATABASE_HOST=cassandra
      - NODE_ID=1
      - MESSAGE_ID_GENERATOR=snowflake
    depends_on:
      - redis
      - cassandra

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042" # doesnt necessary

  redis:
    image: redis:7.0
    ports:
      - "6379:6379" # doesnt necessary

  prometheus:
    image: prom/prometheus:v2.38.0
    ports:
      - "9090:9090" # doesnt necessary
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana:9.1.0
    ports:
      - 3000:3000