apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deploy
  
spec:
  selector:
    matchLabels:
      app: broker

  replicas: 2

  template:
    metadata:
      name: broker-pod
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: harispy/broker:2.4.1
          ports:
            - containerPort: 8000
            - containerPort: 8080
          resources:
            limits:
              cpu: 5250m # 2666m
              memory: 1Gi # 0.5Gi
            requests:
              cpu: 5250m # 666m
              memory: 1Gi # 0.25Gi
          env:
            - name: BROKER_DATABASE
              value: cassandra
            - name: BROKER_DATABASE_HOST
              value: cassandra-svc
            - name: NODE_ID
              value: "1"
            - name: MESSAGE_ID_GENERATOR
              value: redis
            - name: REDIS_ID_GENERATOR_HOST
              value: redis-svc
            - name: DATABASE_BATCH_SIZE
              value: "10000"