apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-graf-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      # - job_name: prometheus
      #   static_configs:
      #     - targets: ["localhost:9090"]
      
      - job_name: broker
        static_configs:
          - targets: ["broker-metric-svc:8000"]

  datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-svc:9090