apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  
spec:
  selector:
    matchLabels:
      app: redis

  replicas: 1

  template:
    metadata:
      name: redis-pod
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: dockerproxy.bale.ai/redis:7.0
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 1300m
              memory: 1Gi
            requests:
              cpu: 1300m
              memory: 1Gi
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          volumeMounts:
              - mountPath: /redis-master
                name: redis-config
      volumes:
        - name: redis-config
          configMap:
            name: redis-no-persistency
            items:
              - key: redis-config
                path: redis.conf